### ISSUE TITLE
Reducing the size on WASM targets

### ISSUE THREAD

**Issue by LaylConway** [seanmonstar/unicase#32]
On WASM targets, this library's unicode lookup table adds roughly 50 KB to release builds.
This makes it the second biggest contributor to my binary size right now, right behind the data section.

I would like to write a PR that on WASM targets uses js-sys's `toLowerCase` instead of the lookup table. This may result in different behavior between WASM and other targets though.

Would a PR like this be accepted? Would it need to be behind a feature gate?

**Comment by LaylConway** [comment]
See also, the related issue in pulldown-cmark: https://github.com/raphlinus/pulldown-cmark/issues/357

**Comment by seanmonstar** [comment]
I'm sympathetic to reducing the size on WASM. What were you thinking with regards to using `toLowerCase`? I'm not that familiar with WASM, does that work on `char`s?

**Comment by LaylConway** [comment]
JS does not have a character type, `toLowerCase` only works on strings.
The idea is to eliminate the lookup table, which is the biggest problem, and rely on the browser knowing how to correctly convert a unicode string to lowercase.

Taking a look at the code, it seems the lookup table is only used to convert characters from uppercase to lowercase, if I'm correct? An implementation approach could be to `cfg` the lookup table and the implementations where it's used and add separate ones for the `wasm32` arch that make use of `js-sys`'s bindings to `toLowerCase`.

**Comment by seanmonstar** [comment]
The table is to do [case folding](https://www.w3.org/International/wiki/Case_folding), which as it explains, handles some cases that simply converting to lowercase does not. I don't know if the browser exposes a way to do case folding. If a way is found, using `cfg` is a fine way to change the internals.

**Comment by LaylConway** [comment]
Quickly checking, it does seem like `toLowerCase` and `toUpperCase` handle this correctly.
I could run simply a single character string through `toLowerCase`, and it should give the right result.

**Comment by seanmonstar** [comment]
[Turkish is an example of when upper/lower case fails.](http://www.i18nguy.com/unicode/turkish-i18n.html) Does that pass the test?

Searching for "JavaScript case folding", I see mention of two APIs: [String.prototype.localeCompare](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) and [Intl.Collator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Collator). I have not used either, so I don't know which is better to use.

**Comment by LaylConway** [comment]
I tested that specifically and it does pass the test.

`localeCompare` could be used to avoid doing it character-by-character, which may have a lot of overhead.
Taking that as an approach for the PR, I would re-implement the functions previously using the lookup table, to eliminate it entirely.

- `localCompare` could be used for both `PartialEq` and `Ord`
- `toLocaleLowerCase` could be used for `Hash`

Both set to "en" locale, as recommended the case folding page.

Does that look like a good solution?

**Comment by seanmonstar** [comment]
I believe so!

**Comment by LaylConway** [comment]
I'll leave this issue open, despite my attempt at using js-sys to solve this not working out, as it may be worth investigating how to make the output WASM smaller if possible.

**Comment by seanmonstar** [comment]
Size was greatly reduced in #35.
