### ISSUE TITLE
Creating a case-insensitive HashMap

### ISSUE THREAD

**Issue by PhilipDaniels** [seanmonstar/unicase#43]
Hi, this is more of a query/check my understanding thing than an issue _per se_.

I have quite often wanted to create a HashMap that uses strings as its keys, but compares them case-insensitively. I've now [done this](https://github.com/PhilipDaniels/cihashmap) (code is not yet on crates.io) but I'm not exactly overjoyed with the code as it requires using `Unicase` objects for all the keys. Still, it works.

In comparison, to create such a map in C# you can simply do

    var ciDict = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);

This works without allocating any new objects, it just does all hashing and equality comparisons in a case-insensitive manner.

I was wondering about achieving the same in Rust, and I thought it might be possible if the hash algorithm from Unicase was usable externally so that it could be passed as the hash algorithm for a `HashMap`. But then I realised you also need to have the HashMap use case-insensitive equality comparisons (to deal with the case when hashes collide) and while a HashMap can be parameterized over its hash function, there is no way to parameterize it over its equality function as well.

Anyway, thanks for Unicase, I just wondered if you had ever thought about this use-case. I'm thinking of publishing my CiHashMap on crates.io, even if it's not great it is at least usable.

**Comment by seanmonstar** [comment]
Yes, having a case-insensitive hashmap was the original motivation for this crate. 

If you're used to Java, you may be worried that creating a `UniCase` is allocating a new object to wrap a string, but in Rust it's not allocating any new memory. It's also why in Rust the comparators are done with wrapper types, since you implement `Ord`, `Eq`, and `Hash` on a type directly.

**Comment by PhilipDaniels** [comment]
Thanks for the quick reply. I think I get what you mean, I sort of suspected that the use of a wrapper type would get optimised away, but I don't know enough x64 assembly to check :-( I couldn't find any existing published crates that did this, so I think I will go ahead and publish mine. Even if it's not perfect someone else might come along and suggest improvements.
