### ISSUE TITLE
Use transparent representation to allow casts

### ISSUE THREAD

**Issue by Plecra** [seanmonstar/unicase#46]
A `repr(transparent)` annotation would allow users to (soundly) cast pointers to `T`s to `UniCase<T>`s. This is handy when you can't trivially dereference the pointer, which can come up in generic code.

- Also mentioned here: https://github.com/seanmonstar/unicase/issues/22#issuecomment-465491635
- This should be a fairly trivial change. LMK if you want a PR :smiley:

**Comment by ijackson** [comment]
This is not trivial, sadly.  A `UniCase<T>` actually contains an enum, so that it can represent whether the contained object is pure-ascii or not, for optimisation purposes.  So a `UniCase<T>` cannot be cast back and forth with a `T` since the representation is actually different.

**Comment by Plecra** [comment]
Ahw, that's a shame. Nevermind then

**Comment by ijackson** [comment]
But see #49

**Comment by aQaTL** [comment]
How about adding `repr(transparent)` to `unicase::Ascii` then? 
I understand it could seem unintuitive to have it on `Ascii`, but not on `Unicase`, but it would be useful for people that want it to use it as a HashMap key, but only care about ascii strings.
