### ISSUE TITLE
Caseless comparisons not implemented correctly? (Normalization of precomposed / non-composed Unicode text missing)

### ISSUE THREAD

**Issue by d4h0** [seanmonstar/unicase#48]
Hi,

I stumbled upon [this](https://stackoverflow.com/questions/47813162/is-there-any-efficient-way-to-have-a-case-insensitive-string-as-a-hashmap-key) StackOverflow question, where BurntSushi5 (I guess this is @BurntSushi) wrote the following in a comment that proposed UniCase:

> I don't think that crate implements correct caseless comparisons because I don't see any normalization happening. The caseless crate does it correctly (but has a different API, so there might be some trade offs between them): docs.rs/caseless/0.2.0/caseless

Shepmaster provided an example that demonstrates the problem:

```rust
assert_eq!(UniCase::new("Åström"), UniCase::new("Åström")
```

...which fails with:

```
thread 'test:tests::unicase' panicked at 'assertion failed: `(left == right)`
  left: `"Åström"`,
 right: `"A\u{30a}stro\u{308}m"`', test/src/test.rs:112:5
```

I didn't find an existing issue, so I thought I'll just open one.

**Comment by Cognoscan** [comment]
The Unicode normalization and case folding algorithms are separate, so this crate is correct in not applying any normalization as part of the comparison. See [UTR #30: Character Foldings, Section 2.2 Relation to Normalization](https://unicode.org/reports/tr30/tr30-4.html#_Toc22).

If you're looking for a caseless comparison that also has normalization options (NFD or NFKD), then yes, [`caseless`](https://crates.io/crates/caseless) is the right call, as it exposes the case folding algorithm in a way that lets it be composed with normalization.

**Comment by steffahn** [comment]
If this is the correct and intended behavior of this crate, I believe it’s still necessary to explicitly call out in the crate documentation that normalization is ***not*** performed. Case-insensitive comparison that ***does*** do normalization is such a naturally reasonable approach that a “we don’t do normalization, as we never said we would do normalization” approach of documenting what this crate does seems suboptimal.

**Comment by seanmonstar** [comment]
[The second comment](https://github.com/seanmonstar/unicase/issues/48#issuecomment-1132131555) is correct, this crate uses Unicode case-folding, not normalization.
