### ISSUE TITLE
Consider removing version_check

### ISSUE THREAD

**Issue by matklad** [seanmonstar/unicase#54]
This crate currently uses `version_check` to support Rust versions older than `1.36.0`. This is ancient history by Rust's standards, so perhaps it is worth it to remove `build.rs` and `version_check` altogether. The motivation being compilation-time performance --- one less deb and one less `build.rs` would shave off some milliseconds. Not a _huge_ win, of course, but still a meaningful reduction, given crate's popularity.

**Comment by seanmonstar** [comment]
Removed in #70
